services: 
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - ./server/.env.local
    environment:
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - my_network

  # server:
  #   build: ./server
  #   ports:
  #     - 3005:3000
  #   networks:
  #     - my_network
  #   env_file:
  #     - ./server/.env.prod
  #   environment:
  #     - NODE_ENV=prod

  # client:
  #   build: ./client
  #   ports:
  #     - 3001:80
  #   networks:
  #     - my_network

volumes:
  redis_data:

networks:
  my_network:
    driver: bridge